baseURL = "https://keratin7.github.io/"
languageCode = "en-us"
title = "Arnav's homepage"
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.png"
  author = "Arnav Arora"
  description = "Describe your website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "keratin7"
  Email         = "arnav2495@gmail.com"
  Twitter       = "keratin7"
  LinkedIn      = "arnav-arora"
  Stackoverflow = "keratin"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "https://medium.com/@arnavarora_38433"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "https://drive.google.com/open?id=1oyC32fqqKJdFX0C_XTMUAct4l8QjXDGU"
